package com.mitcampus.ams.service;
import com.mitcampus.ams.dto.*;import com.mitcampus.ams.dto.Requests.*;import com.mitcampus.ams.entity.*;import com.mitcampus.ams.repository.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.stream.*;
@Service public class AmsService { final StudentRepository students;final OfficialRepository officials;final AppointmentRepository appointments;final NotificationRepository notifications;final AvailabilityRepository availability;final BCryptPasswordEncoder crypt=new BCryptPasswordEncoder(); public AmsService(StudentRepository s,OfficialRepository o,AppointmentRepository a,NotificationRepository n,AvailabilityRepository v){students=s;officials=o;appointments=a;notifications=n;availability=v;}
 public Map<String,Object> student(Student s){return map("id",s.id,"role","student","Name",s.name,"RegisterNumber",s.registerNumber,"Department",s.department,"Year",s.year,"Email",s.email,"ContactNumber",s.contactNumber); } public Map<String,Object> official(Official o){return map("id",o.id,"role","official","OfficialID",String.valueOf(o.id),"Name",o.name,"EmployeeID",o.employeeId,"Email",o.email,"ContactNumber",o.contactNumber,"Designation",o.designation,"Department",o.department,"Availability","Manage in Availability");}
 @Transactional public Object registerStudent(StudentRegistration r){validPassword(r.password(),r.confirmPassword());if(students.findByEmailIgnoreCase(r.email()).isPresent()||students.existsByRegisterNumber(r.registerNumber()))throw new IllegalArgumentException("Email or register number is already registered.");Student s=new Student();s.name=r.name();s.registerNumber=r.registerNumber();s.department=r.department();s.year=r.year();s.email=r.email();s.contactNumber=r.contactNumber();s.passwordHash=crypt.encode(r.password());return student(students.save(s));}
 @Transactional public Object registerOfficial(OfficialRegistration r){validPassword(r.password(),r.confirmPassword());if(officials.findByEmailIgnoreCase(r.email()).isPresent()||officials.existsByEmployeeId(r.employeeId()))throw new IllegalArgumentException("Email or employee ID is already registered.");Official o=new Official();o.name=r.name();o.employeeId=r.employeeId();o.email=r.email();o.contactNumber=r.contactNumber();o.designation=r.designation();o.department=r.department();o.passwordHash=crypt.encode(r.password());return official(officials.save(o));}
 public Object login(Login r){if("student".equals(r.role())){Student s=students.findByEmailIgnoreCase(r.email()).orElseThrow(()->new IllegalArgumentException("Invalid email or password."));if(!crypt.matches(r.password(),s.passwordHash))throw new IllegalArgumentException("Invalid email or password.");return student(s);} Official o=officials.findByEmailIgnoreCase(r.email()).orElseThrow(()->new IllegalArgumentException("Invalid email or password."));if(!crypt.matches(r.password(),o.passwordHash))throw new IllegalArgumentException("Invalid email or password.");return official(o);}
 public List<Map<String,Object>> officials(String dept){return (dept==null?officials.findAll():officials.findByDepartmentIgnoreCase(dept)).stream().map(this::official).toList();} public Object profile(String role,Long id){return "student".equals(role)?student(students.findById(id).orElseThrow(()->new NoSuchElementException("Student not found."))):official(officials.findById(id).orElseThrow(()->new NoSuchElementException("Official not found.")));}
 @Transactional public Object create(AppointmentRequest r){if(r.requestedDate().isBefore(LocalDate.now()))throw new IllegalArgumentException("Preferred date cannot be in the past.");Appointment a=new Appointment();a.student=students.findById(r.studentId()).orElseThrow(()->new NoSuchElementException("Student not found."));a.official=officials.findById(r.officialId()).orElseThrow(()->new NoSuchElementException("Official not found."));a.purpose=r.purpose();a.description=r.description();a.requestedDate=r.requestedDate();a.preferredTime=r.preferredTime();a=appointments.save(a);note(a.official.id,"official","New appointment request",a.student.name+" requested an appointment for "+a.requestedDate,"REQUEST");return appointment(a);}
 public List<Map<String,Object>> appointmentList(String role,Long id){return ("student".equals(role)?appointments.findByStudentIdOrderByCreatedAtDesc(id):appointments.findByOfficialIdOrderByCreatedAtDesc(id)).stream().map(this::appointment).toList();}
 @Transactional public Object approve(Long id,Decision d){Appointment a=owned(id,d.officialId());a.status="APPROVED";a.allocatedDate=d.allocatedDate();a.allocatedTime=d.allocatedTime();a.remarks=d.remarks();a.updatedAt=LocalDateTime.now();note(a.student.id,"student","Appointment Approved","Your appointment with "+a.official.name+" is scheduled for "+a.allocatedDate+" at "+a.allocatedTime,"APPROVED");return appointment(a);}
 @Transactional public Object reject(Long id,Reject d){Appointment a=owned(id,d.officialId());if(d.remarks()==null||d.remarks().isBlank())throw new IllegalArgumentException("A rejection reason is required.");a.status="REJECTED";a.remarks=d.remarks();a.updatedAt=LocalDateTime.now();note(a.student.id,"student","Appointment Rejected","Your appointment with "+a.official.name+" was rejected: "+a.remarks,"REJECTED");return appointment(a);}
 @Transactional public void saveAvailability(Long oid,AvailabilitySave r){Official o=officials.findById(oid).orElseThrow(()->new NoSuchElementException("Official not found."));availability.deleteByOfficialId(oid);for(AvailabilityItem i:r.items()){Availability a=new Availability();a.official=o;a.day=i.day();a.startTime=i.startTime();a.endTime=i.endTime();a.available=i.isAvailable();availability.save(a);}}
 public List<Map<String,Object>> notificationList(Long id){return notifications.findByUserIdOrderByCreatedAtDesc(id).stream().map(n->map("NotificationID",n.id,"Title",n.title,"Message",n.message,"Type",n.type,"IsRead",n.read?"TRUE":"FALSE","CreatedAt",n.createdAt.toString())).toList();} @Transactional public void readAll(Long id){notifications.findByUserIdOrderByCreatedAtDesc(id).forEach(n->n.read=true);}
 public List<Map<String,Object>> availability(Long id){return availability.findByOfficialId(id).stream().map(a->map("id",a.id,"day",a.day,"startTime",String.valueOf(a.startTime),"endTime",String.valueOf(a.endTime),"isAvailable",a.available)).toList();}
 public Object dashboard(String role,Long id){List<Appointment> list="student".equals(role)?appointments.findByStudentIdOrderByCreatedAtDesc(id):appointments.findByOfficialIdOrderByCreatedAtDesc(id);long pending=list.stream().filter(a->"PENDING".equals(a.status)).count(),approved=list.stream().filter(a->"APPROVED".equals(a.status)).count(),completed=list.stream().filter(a->"COMPLETED".equals(a.status)).count(),today=list.stream().filter(a->LocalDate.now().equals(a.allocatedDate)).count();return map("pending",pending,"approved",approved,"completed",completed,"today",today,"upcoming",list.stream().filter(a->"APPROVED".equals(a.status)).limit(1).map(this::appointment).toList(),"recent",list.stream().limit(5).map(this::appointment).toList());}
 private Appointment owned(Long id,Long oid){Appointment a=appointments.findById(id).orElseThrow(()->new NoSuchElementException("Appointment not found."));if(!a.official.id.equals(oid))throw new SecurityException("You cannot update this appointment.");return a;} private void note(Long id,String role,String title,String msg,String type){Notification n=new Notification();n.userId=id;n.userRole=role;n.title=title;n.message=msg;n.type=type;notifications.save(n);} private void validPassword(String p,String c){if(!Objects.equals(p,c))throw new IllegalArgumentException("Passwords do not match.");if(p.length()<8)throw new IllegalArgumentException("Password must be at least 8 characters.");} private Map<String,Object> appointment(Appointment a){return map("AppointmentID",String.valueOf(a.id),"StudentName",a.student.name,"OfficialName",a.official.name,"Purpose",a.purpose,"Description",a.description,"RequestedDate",String.valueOf(a.requestedDate),"PreferredTime",String.valueOf(a.preferredTime),"AllocatedDate",a.allocatedDate==null?null:String.valueOf(a.allocatedDate),"AllocatedTime",a.allocatedTime==null?null:String.valueOf(a.allocatedTime),"Status",a.status,"Remarks",a.remarks,"CreatedAt",a.createdAt.toString());} private Map<String,Object> map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}}
