spring.application.name=mit-campus-ams
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB
spring.datasource.username=ams
spring.datasource.password=ams0004
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
